import { CheckerAction, type SyntaxTableEntry } from "@src/interface/visitor/SyntaxChecker";
import { ComposedTokenType, TokenType } from "@src/interface/visitor/Token";
import { SyntaxState } from "./SyntaxCheckerState";
import { ADDITIONAL_TOKEN, DATA_DECLARATION, LOGIC_ERROR, NO_TEXT_LABEL, WARNING_LABEL } from "./ErrorAndWarning";

export const SYNTAX_TABLE: Record<SyntaxState, Record<TokenType | ComposedTokenType, SyntaxTableEntry>> = {
    [SyntaxState.INITIAL]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.SHIFT, number: SyntaxState.TEXT_INITIAL },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [TokenType.NUMBER]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.ERROR, message: NO_TEXT_LABEL },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.SHIFT, number: SyntaxState.COMPLETE_PROGRAM },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_INITIAL },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
    },
    [SyntaxState.COMPLETE_PROGRAM]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.NUMBER]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.ERROR, message: ADDITIONAL_TOKEN },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ACCEPT, },
    },
    [SyntaxState.DATA_INITIAL]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_PRESENT },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_REDUCTION },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.PROGRAM_DATA },
    },
    [SyntaxState.DATA_REDUCTION]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.PROGRAM },
    },
    [SyntaxState.DATA_PRESENT]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.PROGRAM_DATA },
    },
    [SyntaxState.DATA_BLOCK]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_LABEL_INIT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_ALONE_NUMBER, },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_END },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    [SyntaxState.DATA_LABEL_INIT]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.ERROR, message: DATA_DECLARATION },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.ERROR, message: DATA_DECLARATION },
        [TokenType.DATA_LABEL]: { type: CheckerAction.ERROR, message: DATA_DECLARATION },
        [TokenType.NUMBER]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_NUMBER },
        [TokenType.OPERATION]: { type: CheckerAction.ERROR, message: DATA_DECLARATION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.SHIFT, message: WARNING_LABEL, number: SyntaxState.DATA_NUMBER },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
    },
    [SyntaxState.DATA_END]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA },
    },
    [SyntaxState.DATA_NUMBER]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_LABEL_INIT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_ALONE_NUMBER, },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.SHIFT, number: SyntaxState.COMPLETE_DATA_LABEL },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    [SyntaxState.COMPLETE_DATA_LABEL]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 3, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    [SyntaxState.TEXT_INITIAL]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: SyntaxState.REDUCE_LABEL },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.SHIFT, number: SyntaxState.DETECT_OPERATION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.SHIFT, number: SyntaxState.REDUCE_INST },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.SHIFT, number: SyntaxState.TEXT_BLOCK },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.SHIFT, number: SyntaxState.TEXT_END },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
    },
    [SyntaxState.TEXT_END]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT },
    },
    [SyntaxState.REDUCE_INST]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
    },
    [SyntaxState.REDUCE_LABEL]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 1, reducedAddition: ComposedTokenType.STATEMENT },
    },
    [SyntaxState.DETECT_OPERATION]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.OP_REDUCE, },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.OP_REDUCE, },
        [TokenType.DATA_LABEL]: { type: CheckerAction.OP_REDUCE, },
        [TokenType.NUMBER]: { type: CheckerAction.OP_REDUCE, },
        [TokenType.OPERATION]: { type: CheckerAction.OP_REDUCE, },
        [TokenType.REGISTER]: { type: CheckerAction.OP_REDUCE, },
        [TokenType.WORD]: { type: CheckerAction.OP_REDUCE, },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.OP_REDUCE, },
    },
    [SyntaxState.TEXT_BLOCK]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: SyntaxState.REDUCE_LABEL },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.SHIFT, number: SyntaxState.DETECT_OPERATION },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.SHIFT, number: SyntaxState.REDUCE_INST },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.SHIFT, number: SyntaxState.TEXT_BLOCK },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.SHIFT, number: SyntaxState.STATEMENT_REDUCTION, },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.TEXT_BLOCK },
    },
    [SyntaxState.STATEMENT_REDUCTION]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.TEXT_BLOCK },
    },
    [SyntaxState.DATA_ALONE_NUMBER]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_LABEL_INIT, },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_ALONE_NUMBER, },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.SHIFT, number: SyntaxState.DATA_ALONE_NUMBER_REDUCE },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 0, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
    [SyntaxState.DATA_ALONE_NUMBER_REDUCE]: {
        [TokenType.BLANK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.COMMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.TEXT_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.DATA_LABEL]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.NUMBER]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.OPERATION]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [TokenType.REGISTER]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [TokenType.WORD]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA_BLOCK },
        [ComposedTokenType.DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.DATA_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.INSTRUCTION]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.PROGRAM_DATA]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.STATEMENT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.TEXT_BLOCK]: { type: CheckerAction.ERROR, message: LOGIC_ERROR },
        [ComposedTokenType.END_OF_CODE]: { type: CheckerAction.REDUCE, number: 2, reducedAddition: ComposedTokenType.DATA_BLOCK },
    },
};
